// frontend-react/src/Components/Counting/Counting.tsx
import React from 'react'

import data from '../../Supports/Data/Chart'
import style from './Counting.module.scss'
import { Line } from 'react-chartjs-2';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';

// Registrace potřebných komponent pro Line graf
ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

const Counting = () => {
  const data = {
    type: 'bar',
    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    datasets: [
      {
        label: 'Počet návštěv',
        data: [65, 59, 80, 81, 56, 55],
        fill: false,
        backgroundColor: 'rgb(75,192,192)',
        borderColor: 'rgba(75,192,192,0.2)',
      },
    ],
  };
  
  const options = {
    scales: {
      y: {
        beginAtZero: true,
      },
    },
  };
  
  const LineChart: React.FC =()=> {
    return <Line data={data} options={options} />;
  }

  return (
    <div className={style['Counting']}>
      <div className={style['Counting__Row']}>
        <h3>Přehled</h3>
        <button>Srpen</button>
      </div>
      <div className={style['Counting__Chart']}>
      <LineChart />
      </div>
    </div>
  )
}

export default Counting

// frontend-vue/src/components/CountingComponent.vue
<script>
import { Chart, BarController, BarElement, CategoryScale, LinearScale } from 'chart.js';

// Registrace komponentů potřebných pro barový graf
Chart.register(BarController, BarElement, CategoryScale, LinearScale);

export default {
  mounted() {
    const ctx = document.getElementById('myChart').getContext('2d');
    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        datasets: [{
          label: '# of Votes',
          data: [12, 19, 3, 5, 2, 3],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  }
}
</script>


<template>
  <div class="Counting">
    <div class="Counting__Row">
      <h3>Přehled</h3>
      <button>Srpen</button>
    </div>
    <div class="Counting__Chart">
      <canvas id="myChart"></canvas>
    </div>
  </div>
</template>


<style scoped lang="scss">
@import '../assets/styles/variables.scss';
.Counting{
    display: flex;
    flex-direction: column;
    padding: 6px 12px;
    width: 70%;
    height: 100%;
    border: 1px solid #c5c5c5;
    border-radius: 12px;
   
    &__Chart{
        width: 100%;
    }
    &__Row{
        display: flex;
        flex-direction: row;
        width: 100%;
        justify-content: space-around;
        align-items: center;
    }
}
</style>
