// frontend-react/src/Components/Inventory/Inventory.tsx
import React, { useState } from 'react'
import Data from '../../Supports/Data/Inventory.js'
import style from './Invetory.module.scss'
import { useModal } from '../Modal/Modal.tsx';


const InventoryComponent = () => {
    const inventory = Data.map((item) => item)
    const [isModalOpen, setModalOpen] = useState(false)

    const Table = () => {
        const { openModal } = useModal();
        return (
            <table className={style['Table']}>
                <tbody>
                <tr>
                    <th>Název</th>
                    <th>Na skladě</th>
                    <th>Price</th>
                    <th>Akce</th>
                </tr>
                {inventory.map((item) =>
                    <tr key={item.id}>
                        <td>{item.name}</td>
                        <td>{item.price}</td>
                        <td>{item.qty}</td>
                        <td><button onClick={openModal}>Přidat</button> | <button>Odebrat</button></td>
                    </tr>
                )}
                </tbody>
            </table>
        )
    }

    return (
        <div className={style['Inventory']}>
            <h3>Sklad</h3>
            <div>
                <Table />

            </div>
        </div>
    )
}

export default InventoryComponent

// frontend-vue/src/components/InventoryComponent.vue
<script setup lang="js">
import Data from '@/Supports/Data/Inventory.js';
import { useModalState } from '../Supports/useModalState';

const {openModal} = useModalState()
</script>

<template>
    <div class="Inventory">
        <h3>Sklad</h3>
        <div>
            <table class="Table">
        <tbody>
            <tr>
            <th>Název</th>
            <th>Na skladě</th>
            <th>Price</th>
            <th>Akce</th>
        </tr>
        <tr v-for="item in Data" :key="item.id">
            <td>{{ item.name }}</td>
            <td>{{item.price}}</td>
            <td>{{item.qty}}</td>
            <td><button @click="openModal">Přidat</button> | <button>Odebrat</button></td>
        </tr>
        </tbody>
    </table>
        </div>
    </div>
</template>

<style scoped lang="scss">
.Inventory{
    width: 100%;
    padding: 6px 12px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

.Table{
    width: 100%;
    padding: 12px;
    border: 1px solid #c5c5c5;
    border-radius: 10px;
    tr{
        font-size: 1.5rem;
    }
    th{
        align-items: flex-start;
        padding: 12px;
    }
    td{
      text-align: center;
    }
}
</style>
